sudo: required
services:
  - docker

before_install:
  - docker build -t haris/docker-react -f Dockerfile.dev .

script:
  # - docker run -e CI=true haris/docker-react npm run test -- --coverage
  - docker run haris/docker-react npm run test -- --coverage

# deploy:
#   provider: elasticbeanstalk
